### ISSUE TITLE
Plugin Serveur ? 

### ISSUE THREAD

**Issue by Faynix-code** [AzuriomCommunity/Plugin-SkinAPI#1]
>Bonjour je n'ai pas très bien compris le principe de ce plugin. Es ce que on mets le plugin sur le serveur ou pas car après mes nombreuse recherche je ne trouve pas le .jar du plugin. 

Cordialement

**Comment by MrMicky-FR** [comment]
Ce plugin est destiné aux serveurs qui utilisent des modifications du coté du client Minecraft (typiquement avec un launcher custom). 

Étant donné que le client Minecraft officiel ne peux afficher que des skins signés par Mojang, il est assez compliqué de faire un plugin de ce type étant donné que ça demande d'upload le skin sur un compte Minecraft premium, et donc ça oblige à passer par des services externes pas forcément toujours fonctionnels, ou d'avoir un compte Minecraft juste pour générer les skins
