### ISSUE TITLE
Add custom save skin png

### ISSUE THREAD

**Issue by TheMrMes109** [AzuriomCommunity/Plugin-SkinAPI#16]
Add custom save skin png

Now skins are saved in /azuriom/storage/app/public/skins ID.png

I would like to be able to change the path /azuriom/storage/app/public/skins/(Select path)/(username or id).png

**Comment by TheMrMes109** [comment]
custom launcher and mod for skins uses links where the player's nickname is .png
I can tell it example.net/skins which will lead to the SkinAPI skins folder (/var/www/azuriom/storage/app/public/skins/%username%.png )
But your plugin store skins in ID and not nickname

**Comment by Javdu10** [comment]
@TheMrMes109 i have updated the description here : https://market.azuriom.com/resources/18

It's already possible to use nickname as for the path there is no reason for it to change
